/**
 * Offline cache service for The Floor.
 *
 * Downloads every sample category into a dedicated Cache Storage bucket so the
 * app works fully offline. The service worker generated by vite-plugin-pwa owns
 * a CacheFirst runtime route pointing at the SAME cache name ({@link CATEGORY_CACHE}),
 * so any runtime `fetch('/categories/*.json')` is served from this cache when the
 * network is unavailable.
 *
 * The cache key written here MUST be byte-identical to the URL requested at
 * runtime by `fetchSampleCategory` — both use `getSampleCategoryUrl()` to
 * guarantee that.
 */

import { getSampleCategories, getSampleCategoryUrl } from '@utils/sampleCategories';
import { getStorageEstimate } from '@storage/indexedDB';
import { createLogger } from '@utils/logger';

const log = createLogger('OfflineCache');

/**
 * Cache Storage bucket name for sample categories.
 * MUST match the `runtimeCaching` cacheName configured in `vite.config.ts`.
 */
export const CATEGORY_CACHE = 'floor-categories-v1';

/** localStorage key holding the last successful download summary. */
export const OFFLINE_READY_KEY = 'offline-cache-status';

/** Number of files downloaded in parallel. Bounded to limit peak memory. */
const CONCURRENCY = 3;

export interface OfflineSummary {
  /** ISO timestamp of the last fully-successful download. */
  downloadedAt: string;
  /** Number of category files cached at that time. */
  fileCount: number;
  /** Total bytes downloaded. */
  totalBytes: number;
  /** Whether the browser granted persistent storage. */
  persisted: boolean;
}

export interface OfflineStatus {
  /** True when every sample category is cached. */
  ready: boolean;
  /** Number of category files currently in the cache. */
  cachedCount: number;
  /** Total number of sample categories. */
  totalCount: number;
  /** Bytes used by the origin (all storage types). */
  usage: number;
  /** Bytes available to the origin. */
  quota: number;
  /** Last successful download summary, if any. */
  summary: OfflineSummary | null;
}

export interface DownloadProgress {
  /** Files fully cached so far. */
  completed: number;
  /** Total files to cache. */
  total: number;
  /** Bytes downloaded so far across all files. */
  bytes: number;
  /** Filename most recently progressed. */
  currentName: string;
}

export type ProgressCallback = (progress: DownloadProgress) => void;

/** True when the Cache Storage + Service Worker APIs are available. */
export function isOfflineSupported(): boolean {
  return typeof caches !== 'undefined' && 'serviceWorker' in navigator;
}

function isQuotaError(error: unknown): boolean {
  return (
    error instanceof DOMException &&
    (error.name === 'QuotaExceededError' || error.name === 'QUOTA_EXCEEDED_ERR')
  );
}

function isAbortError(error: unknown): boolean {
  return error instanceof DOMException && error.name === 'AbortError';
}

function isOfflineSummary(value: unknown): value is OfflineSummary {
  if (typeof value !== 'object' || value === null) {
    return false;
  }
  const record = value as Record<string, unknown>;
  return (
    typeof record['downloadedAt'] === 'string' &&
    typeof record['fileCount'] === 'number' &&
    typeof record['totalBytes'] === 'number' &&
    typeof record['persisted'] === 'boolean'
  );
}

function saveSummary(summary: OfflineSummary): void {
  try {
    localStorage.setItem(OFFLINE_READY_KEY, JSON.stringify(summary));
  } catch (error) {
    log.warn('Failed to persist offline summary', error);
  }
}

function loadSummary(): OfflineSummary | null {
  try {
    const raw = localStorage.getItem(OFFLINE_READY_KEY);
    if (!raw) {
      return null;
    }
    const parsed: unknown = JSON.parse(raw);
    return isOfflineSummary(parsed) ? parsed : null;
  } catch {
    return null;
  }
}

/**
 * Fetch a single category and store it in the cache, reporting decoded bytes as
 * they stream in. The original response is cached as-is (preserving headers and
 * body); a cloned branch is read purely to drive progress, so the cache write
 * and the progress read proceed in parallel. Returns the number of bytes seen.
 */
async function downloadOne(
  cache: Cache,
  filename: string,
  onBytes: (chunkLength: number) => void,
  signal: AbortSignal | undefined
): Promise<number> {
  const url = getSampleCategoryUrl(filename);
  const init: RequestInit = signal ? { signal } : {};
  const response = await fetch(url, init);

  if (!response.ok) {
    throw new Error(`Failed to fetch ${filename}: ${String(response.status)}`);
  }

  // Write the untouched response to the cache; read the clone for progress.
  const cacheWrite = cache.put(url, response.clone());

  let size = 0;
  const body = response.body;
  if (body) {
    const reader = body.getReader();
    for (;;) {
      const { done, value } = await reader.read();
      if (done) {
        break;
      }
      size += value.byteLength;
      onBytes(value.byteLength);
    }
  } else {
    // No readable stream (e.g. some test mocks): fall back to a buffered read.
    const blob = await response.blob();
    size = blob.size;
    onBytes(size);
  }

  await cacheWrite;
  return size;
}

/**
 * Run an async worker over items with bounded concurrency.
 */
async function runPool<T>(
  items: readonly T[],
  concurrency: number,
  worker: (item: T) => Promise<void>
): Promise<void> {
  let cursor = 0;
  const runner = async (): Promise<void> => {
    while (cursor < items.length) {
      const index = cursor;
      cursor += 1;
      const item = items[index];
      if (item === undefined) {
        continue;
      }
      await worker(item);
    }
  };
  const runnerCount = Math.min(concurrency, items.length);
  await Promise.all(Array.from({ length: runnerCount }, () => runner()));
}

/**
 * Download and cache every sample category for offline use.
 *
 * Idempotent and resumable: files already present in the cache are skipped, so
 * re-running after a cancellation or failure only fetches what is missing.
 *
 * @param onProgress - Called as files and bytes complete.
 * @param signal - Abort signal to cancel an in-flight download.
 * @returns Summary of the download (also persisted to localStorage on full success).
 * @throws If offline caching is unsupported, on abort, or on storage/network errors.
 */
export async function downloadAll(
  onProgress?: ProgressCallback,
  signal?: AbortSignal
): Promise<OfflineSummary> {
  if (!isOfflineSupported()) {
    throw new Error('Offline mode is not supported in this browser.');
  }

  const samples = getSampleCategories();
  const total = samples.length;

  // Ask the browser to keep our (large) cache from being evicted under pressure.
  let persisted = false;
  if ('storage' in navigator && 'persist' in navigator.storage) {
    try {
      persisted = await navigator.storage.persist();
    } catch (error) {
      log.warn('navigator.storage.persist() failed', error);
    }
  }

  const cache = await caches.open(CATEGORY_CACHE);

  let completed = 0;
  let bytes = 0;
  const emit = (currentName: string): void => {
    onProgress?.({ completed, total, bytes, currentName });
  };
  emit('');

  await runPool(samples, CONCURRENCY, async (sample) => {
    if (signal?.aborted) {
      throw new DOMException('Download aborted', 'AbortError');
    }

    const url = getSampleCategoryUrl(sample.filename);
    const existing = await cache.match(url);
    if (existing) {
      const length = existing.headers.get('Content-Length');
      if (length) {
        bytes += Number.parseInt(length, 10) || 0;
      }
      completed += 1;
      emit(sample.filename);
      return;
    }

    try {
      await downloadOne(
        cache,
        sample.filename,
        (chunkLength) => {
          bytes += chunkLength;
          emit(sample.filename);
        },
        signal
      );
    } catch (error) {
      if (isAbortError(error)) {
        throw error;
      }
      if (isQuotaError(error)) {
        throw new Error('Ran out of storage space. Free up space and try downloading again.');
      }
      throw error instanceof Error ? error : new Error(`Failed to cache ${sample.filename}`);
    }

    completed += 1;
    emit(sample.filename);
  });

  const summary: OfflineSummary = {
    downloadedAt: new Date().toISOString(),
    fileCount: completed,
    totalBytes: bytes,
    persisted,
  };

  // Only record "ready" once the full set is cached.
  if (completed >= total && total > 0) {
    saveSummary(summary);
  }

  return summary;
}

/**
 * Report the current offline-readiness: how many categories are cached, the
 * persisted summary (if any), and the origin's storage usage/quota.
 */
export async function getOfflineStatus(): Promise<OfflineStatus> {
  const totalCount = getSampleCategories().length;
  const summary = loadSummary();

  let cachedCount = 0;
  if (isOfflineSupported()) {
    try {
      const cache = await caches.open(CATEGORY_CACHE);
      const keys = await cache.keys();
      cachedCount = keys.length;
    } catch (error) {
      log.warn('Failed to read offline cache', error);
    }
  }

  let usage = 0;
  let quota = 0;
  try {
    const estimate = await getStorageEstimate();
    usage = estimate.usage;
    quota = estimate.quota;
  } catch (error) {
    log.warn('Failed to read storage estimate', error);
  }

  return {
    ready: totalCount > 0 && cachedCount >= totalCount,
    cachedCount,
    totalCount,
    usage,
    quota,
    summary,
  };
}

/**
 * Remove all cached categories and clear the offline-ready flag.
 */
export async function clearOffline(): Promise<void> {
  if (isOfflineSupported()) {
    try {
      await caches.delete(CATEGORY_CACHE);
    } catch (error) {
      log.warn('Failed to delete offline cache', error);
    }
  }
  try {
    localStorage.removeItem(OFFLINE_READY_KEY);
  } catch (error) {
    log.warn('Failed to clear offline flag', error);
  }
}
