/**
 * CardsStep — the third step of the LLM Studio wizard.
 *
 * On entry (with a configured key and an empty list) it makes ONE
 * `generateCardIdeas` call to prepopulate ~50 card ideas, then lets the user
 * curate them: reroll the whole list (confirm-gated), edit a card's answer or
 * image prompt, delete a card (confirm-gated), or append a blank card for
 * manual entry. Each row keys off the card's stable nanoid `id` so deleting or
 * adding mid-list never remounts the wrong row.
 *
 * The initial generation and "reroll all" share ONE async path: both call
 * `generateCardIdeas` once and dispatch `SET_CARDS`, both show the single
 * overlay spinner, and both surface a typed {@link GenerationError} with Retry.
 *
 * State (the `cards` list) lives in the parent's `useStudioState` draft and is
 * threaded in via props; this component owns only the transient generate/error
 * UI flags. Slides are derived by the reducer when advancing to `images`, so
 * this step never derives them — it only edits idea text. Per-card image
 * generation/status is Task 58 and intentionally absent here.
 */

import { type DragEvent, useCallback, useEffect, useRef, useState } from 'react';
import type { CardIdea } from '@types';
import { Button } from '@components/common/Button';
import { useCredentials } from '@hooks/useCredentials';
import { generateCardIdeas, toGenerationError, type GenerationError } from '@services/openai';
import { CardListItem } from '@components/studio/CardListItem';
import { moveCard } from '@utils/reorder';
import styles from './CardsStep.module.css';

/** Default number of card ideas to request (matches the ~50-slide sample norm). */
export const DEFAULT_CARD_COUNT = 50;

/**
 * How far the curated list may drift from {@link DEFAULT_CARD_COUNT} before we
 * show a soft, non-blocking warning. Sample categories carry 41–52 slides.
 */
const COUNT_WARNING_MARGIN = 15;

/**
 * The custom drag MIME type. A typed key (rather than the default `text/plain`)
 * keeps these card drags from being confused with arbitrary text drops, and the
 * payload is the dragged card's stable `id` so the drop resolves by identity
 * even if the list mutates mid-drag.
 */
const CARD_DRAG_MIME = 'application/x-floor-card-id';

export interface CardsStepProps {
  /** The confirmed category name (from the previous step's draft). */
  categoryName: string;
  /** The current card list (owned by the wizard draft). */
  cards: CardIdea[];
  /** Replace the whole list → `SET_CARDS` (initial generate + reroll-all). */
  onSetCards: (cards: CardIdea[]) => void;
  /** Edit one card's generated fields → `UPDATE_CARD`. */
  onUpdateCard: (id: string, changes: Partial<Omit<CardIdea, 'id'>>) => void;
  /** Remove one card → `DELETE_CARD`. */
  onDeleteCard: (id: string) => void;
  /** Append a blank card → `ADD_CARD`. */
  onAddCard: () => void;
  /** Advance to the images step (gated by the parent's `canAdvance`). */
  onContinue: () => void;
}

export function CardsStep({
  categoryName,
  cards,
  onSetCards,
  onUpdateCard,
  onDeleteCard,
  onAddCard,
  onContinue,
}: CardsStepProps) {
  const [config, { isConfigured }] = useCredentials();

  const [isGenerating, setIsGenerating] = useState(false);
  const [error, setError] = useState<GenerationError | null>(null);
  const [confirmReroll, setConfirmReroll] = useState(false);

  // Live native-drag state. `draggingId` is the card being dragged; `dropIndex`
  // is the insertion point (0..length) the drop would land at. Both are null
  // when no drag is in progress. Kept here (not in the row) so the indicator and
  // the source-dim are computed in one place.
  const [draggingId, setDraggingId] = useState<string | null>(null);
  const [dropIndex, setDropIndex] = useState<number | null>(null);

  // Guards a single auto-generation on entry. A ref (not state) so React 19's
  // double-invoked effects in dev/strict mode don't fire two API calls, and so
  // it survives re-renders without retriggering generation.
  const hasAutoGeneratedRef = useRef(false);
  // The latest in-flight request id; a stale resolution is ignored so a fast
  // reroll can't be clobbered by an earlier, slower call.
  const requestIdRef = useRef(0);

  /**
   * The single async path shared by initial generation and reroll-all: one
   * `generateCardIdeas` call, one `SET_CARDS` dispatch, one spinner, one typed
   * error with retry.
   */
  const generate = useCallback(async () => {
    if (!isConfigured) return;
    const requestId = requestIdRef.current + 1;
    requestIdRef.current = requestId;

    setIsGenerating(true);
    setError(null);
    try {
      const generated = await generateCardIdeas(config, categoryName, DEFAULT_CARD_COUNT);
      if (requestIdRef.current !== requestId) return; // superseded
      onSetCards(generated);
    } catch (caught) {
      if (requestIdRef.current !== requestId) return; // superseded
      // generateCardIdeas throws GenerationError; normalize defensively so any
      // unexpected throw still surfaces an actionable, retryable message.
      setError(toGenerationError(caught));
    } finally {
      if (requestIdRef.current === requestId) {
        setIsGenerating(false);
      }
    }
  }, [config, categoryName, isConfigured, onSetCards]);

  // Auto-generate exactly once on initial entry: when we have a key and the
  // list is empty on mount. The `cards.length` check reads the value at the
  // moment the effect first becomes eligible (it is intentionally NOT a
  // dependency) so that later manually emptying the list — e.g. deleting every
  // card — does NOT retrigger generation. A resumed draft that already has
  // cards skips this and shows them directly.
  const cardsCountRef = useRef(cards.length);
  cardsCountRef.current = cards.length;
  useEffect(() => {
    if (hasAutoGeneratedRef.current) return;
    if (!isConfigured) return;
    // Mark auto-generation resolved as soon as we're eligible to decide, so it
    // can only ever happen once regardless of subsequent list changes.
    hasAutoGeneratedRef.current = true;
    if (cardsCountRef.current > 0) return;
    void generate();
  }, [isConfigured, generate]);

  const handleRerollConfirmed = () => {
    setConfirmReroll(false);
    void generate();
  };

  // --- reordering ------------------------------------------------------------
  // Both the keyboard Move buttons and native drag-and-drop funnel through
  // `reorder`, which dispatches `SET_CARDS` with the new order. Because slide
  // image/censor data is keyed by card id and `SET_CARDS` preserves it, each
  // card's eventual image follows it to the new position.

  const reorder = useCallback(
    (from: number, to: number) => {
      const next = moveCard(cards, from, to);
      // Skip the dispatch when nothing actually moved (e.g. dropping a card on
      // itself, or moving past an end).
      if (next.length === cards.length && next.every((card, i) => card.id === cards[i]?.id)) {
        return;
      }
      onSetCards(next);
    },
    [cards, onSetCards]
  );

  const moveUp = useCallback(
    (index: number) => {
      reorder(index, index - 1);
    },
    [reorder]
  );

  const moveDown = useCallback(
    (index: number) => {
      // Target index `index + 2` lands the card after its current next neighbor
      // (insert-before semantics), i.e. one slot later.
      reorder(index, index + 2);
    },
    [reorder]
  );

  const handleDragStart = useCallback((e: DragEvent<HTMLLIElement>, id: string) => {
    setDraggingId(id);
    e.dataTransfer.effectAllowed = 'move';
    e.dataTransfer.setData(CARD_DRAG_MIME, id);
  }, []);

  const handleDragOver = useCallback(
    (e: DragEvent<HTMLLIElement>, index: number) => {
      if (draggingId === null) return;
      // Allow the drop and compute the insertion point: before or after the
      // hovered row depending on which half the pointer is over.
      e.preventDefault();
      e.dataTransfer.dropEffect = 'move';
      const rect = e.currentTarget.getBoundingClientRect();
      const after = e.clientY - rect.top > rect.height / 2;
      setDropIndex(after ? index + 1 : index);
    },
    [draggingId]
  );

  const clearDrag = useCallback(() => {
    setDraggingId(null);
    setDropIndex(null);
  }, []);

  const handleDrop = useCallback(
    (e: DragEvent<HTMLLIElement>, index: number) => {
      if (draggingId === null) {
        clearDrag();
        return;
      }
      e.preventDefault();
      const from = cards.findIndex((card) => card.id === draggingId);
      // Resolve the drop position the same way `handleDragOver` did, so a drop
      // without a final dragover (rare) still lands correctly.
      const rect = e.currentTarget.getBoundingClientRect();
      const after = e.clientY - rect.top > rect.height / 2;
      const to = after ? index + 1 : index;
      clearDrag();
      if (from >= 0) {
        reorder(from, to);
      }
    },
    [cards, draggingId, reorder, clearDrag]
  );

  const cardCount = cards.length;
  // Defensive runtime guard: `answer` is typed as a string, but a malformed
  // card must never crash the render, so coalesce before trimming. The lint
  // rule trusts the static type and flags the `??` as unnecessary; we keep it
  // intentionally for resilience.
  const answeredCount = cards.filter(
    // eslint-disable-next-line @typescript-eslint/no-unnecessary-condition
    (card) => (card.answer ?? '').trim().length > 0
  ).length;
  const canContinue = answeredCount > 0;
  const countLabel =
    `${String(cardCount)} ${cardCount === 1 ? 'card' : 'cards'}` +
    (answeredCount !== cardCount ? ` (${String(answeredCount)} with an answer)` : '');
  const countDriftsFar =
    cardCount > 0 && Math.abs(cardCount - DEFAULT_CARD_COUNT) > COUNT_WARNING_MARGIN;

  const stepClass = styles['step'] ?? '';
  const introClass = styles['intro'] ?? '';
  const toolbarClass = styles['toolbar'] ?? '';
  const countClass = styles['count'] ?? '';
  const toolbarActionsClass = styles['toolbarActions'] ?? '';
  const warningClass = styles['warning'] ?? '';
  const listWrapClass = styles['listWrap'] ?? '';
  const listClass = styles['list'] ?? '';
  const emptyClass = styles['empty'] ?? '';
  const overlayClass = styles['overlay'] ?? '';
  const spinnerClass = styles['spinner'] ?? '';
  const errorClass = styles['error'] ?? '';
  const errorIconClass = styles['errorIcon'] ?? '';
  const errorMessageClass = styles['errorMessage'] ?? '';
  const errorActionsClass = styles['errorActions'] ?? '';
  const footerClass = styles['footer'] ?? '';
  const confirmBarClass = styles['confirmBar'] ?? '';

  if (!isConfigured) {
    return (
      <div className={stepClass}>
        <p className={introClass}>
          Add your OpenAI key on the credentials step to generate card ideas for &ldquo;
          {categoryName}&rdquo;.
        </p>
      </div>
    );
  }

  return (
    <div className={stepClass}>
      <p className={introClass}>
        Card ideas for &ldquo;{categoryName}&rdquo;. Edit any answer or image prompt, delete cards
        you don&rsquo;t want, add your own, or reroll the whole set. Images come next.
      </p>

      <div className={toolbarClass}>
        <span className={countClass} role="status">
          {countLabel}
        </span>
        <div className={toolbarActionsClass}>
          <Button
            type="button"
            variant="secondary"
            size="small"
            onClick={() => {
              // Wrap so the click event is not forwarded as `addCard`'s `card`
              // argument (which would store the event as a malformed card).
              onAddCard();
            }}
          >
            + Add card
          </Button>
          <Button
            type="button"
            variant="danger"
            size="small"
            onClick={() => {
              setConfirmReroll(true);
            }}
            disabled={isGenerating}
          >
            🎲 Reroll all
          </Button>
        </div>
      </div>

      {countDriftsFar && (
        <p className={warningClass} role="status">
          This category has {cardCount} cards — sample categories usually carry around{' '}
          {DEFAULT_CARD_COUNT}. That&rsquo;s fine, just a heads-up.
        </p>
      )}

      {confirmReroll && (
        <div className={confirmBarClass} role="alertdialog" aria-label="Confirm reroll all">
          <span>Replace all {cardCount} cards with a fresh set? Your edits will be lost.</span>
          <div className={errorActionsClass}>
            <Button
              type="button"
              variant="secondary"
              size="small"
              onClick={() => {
                setConfirmReroll(false);
              }}
            >
              Cancel
            </Button>
            <Button type="button" variant="danger" size="small" onClick={handleRerollConfirmed}>
              Reroll all
            </Button>
          </div>
        </div>
      )}

      {error !== null && (
        <div className={errorClass} role="alert">
          <span className={errorIconClass} aria-hidden="true">
            ⚠️
          </span>
          <div>
            <p className={errorMessageClass}>{error.message}</p>
            <div className={errorActionsClass}>
              <Button
                type="button"
                variant="secondary"
                size="small"
                onClick={() => {
                  void generate();
                }}
              >
                Retry
              </Button>
            </div>
          </div>
        </div>
      )}

      <div className={listWrapClass}>
        {isGenerating && (
          <div className={overlayClass} role="status" aria-live="polite">
            <span className={spinnerClass} aria-hidden="true">
              ⏳
            </span>
            <span>Generating card ideas…</span>
          </div>
        )}

        {cardCount === 0 && !isGenerating ? (
          <p className={emptyClass}>
            No cards yet. Reroll to generate a fresh set, or add one manually.
          </p>
        ) : (
          <ul className={listClass}>
            {cards.map((card, index) => (
              <CardListItem
                key={card.id}
                card={card}
                position={index + 1}
                total={cardCount}
                onChange={(changes) => {
                  onUpdateCard(card.id, changes);
                }}
                onDelete={() => {
                  onDeleteCard(card.id);
                }}
                onMoveUp={() => {
                  moveUp(index);
                }}
                onMoveDown={() => {
                  moveDown(index);
                }}
                isDragging={draggingId === card.id}
                isDropBefore={dropIndex === index && draggingId !== null}
                isDropAfter={
                  dropIndex === index + 1 && index === cardCount - 1 && draggingId !== null
                }
                onDragStart={(e) => {
                  handleDragStart(e, card.id);
                }}
                onDragOver={(e) => {
                  handleDragOver(e, index);
                }}
                onDrop={(e) => {
                  handleDrop(e, index);
                }}
                onDragEnd={clearDrag}
              />
            ))}
          </ul>
        )}
      </div>

      <div className={footerClass}>
        <Button
          type="button"
          variant="primary"
          onClick={onContinue}
          disabled={!canContinue || isGenerating}
        >
          Continue →
        </Button>
      </div>
    </div>
  );
}
