/**
 * CardsStep — the third step of the LLM Studio wizard.
 *
 * On entry (with a configured key and an empty list) it makes ONE
 * `generateCardIdeas` call to prepopulate ~50 card ideas, then lets the user
 * curate them: reroll the whole list (confirm-gated), edit a card's answer or
 * image prompt, delete a card (confirm-gated), or append a blank card for
 * manual entry. Each row keys off the card's stable nanoid `id` so deleting or
 * adding mid-list never remounts the wrong row.
 *
 * The initial generation and "reroll all" share ONE async path: both call
 * `generateCardIdeas` once and dispatch `SET_CARDS`, both show the single
 * overlay spinner, and both surface a typed {@link GenerationError} with Retry.
 *
 * State (the `cards` list) lives in the parent's `useStudioState` draft and is
 * threaded in via props; this component owns only the transient generate/error
 * UI flags. Slides are derived by the reducer when advancing to `images`, so
 * this step never derives them — it only edits idea text. Per-card image
 * generation/status is Task 58 and intentionally absent here.
 */

import { useCallback, useEffect, useRef, useState } from 'react';
import type { CardIdea } from '@types';
import { Button } from '@components/common/Button';
import { useCredentials } from '@hooks/useCredentials';
import { generateCardIdeas, toGenerationError, type GenerationError } from '@services/openai';
import { CardListItem } from '@components/studio/CardListItem';
import styles from './CardsStep.module.css';

/** Default number of card ideas to request (matches the ~50-slide sample norm). */
export const DEFAULT_CARD_COUNT = 50;

/**
 * How far the curated list may drift from {@link DEFAULT_CARD_COUNT} before we
 * show a soft, non-blocking warning. Sample categories carry 41–52 slides.
 */
const COUNT_WARNING_MARGIN = 15;

export interface CardsStepProps {
  /** The confirmed category name (from the previous step's draft). */
  categoryName: string;
  /** The current card list (owned by the wizard draft). */
  cards: CardIdea[];
  /** Replace the whole list → `SET_CARDS` (initial generate + reroll-all). */
  onSetCards: (cards: CardIdea[]) => void;
  /** Edit one card's generated fields → `UPDATE_CARD`. */
  onUpdateCard: (id: string, changes: Partial<Omit<CardIdea, 'id'>>) => void;
  /** Remove one card → `DELETE_CARD`. */
  onDeleteCard: (id: string) => void;
  /** Append a blank card → `ADD_CARD`. */
  onAddCard: () => void;
  /** Advance to the images step (gated by the parent's `canAdvance`). */
  onContinue: () => void;
}

export function CardsStep({
  categoryName,
  cards,
  onSetCards,
  onUpdateCard,
  onDeleteCard,
  onAddCard,
  onContinue,
}: CardsStepProps) {
  const [config, { isConfigured }] = useCredentials();

  const [isGenerating, setIsGenerating] = useState(false);
  const [error, setError] = useState<GenerationError | null>(null);
  const [confirmReroll, setConfirmReroll] = useState(false);

  // Guards a single auto-generation on entry. A ref (not state) so React 19's
  // double-invoked effects in dev/strict mode don't fire two API calls, and so
  // it survives re-renders without retriggering generation.
  const hasAutoGeneratedRef = useRef(false);
  // The latest in-flight request id; a stale resolution is ignored so a fast
  // reroll can't be clobbered by an earlier, slower call.
  const requestIdRef = useRef(0);

  /**
   * The single async path shared by initial generation and reroll-all: one
   * `generateCardIdeas` call, one `SET_CARDS` dispatch, one spinner, one typed
   * error with retry.
   */
  const generate = useCallback(async () => {
    if (!isConfigured) return;
    const requestId = requestIdRef.current + 1;
    requestIdRef.current = requestId;

    setIsGenerating(true);
    setError(null);
    try {
      const generated = await generateCardIdeas(config, categoryName, DEFAULT_CARD_COUNT);
      if (requestIdRef.current !== requestId) return; // superseded
      onSetCards(generated);
    } catch (caught) {
      if (requestIdRef.current !== requestId) return; // superseded
      // generateCardIdeas throws GenerationError; normalize defensively so any
      // unexpected throw still surfaces an actionable, retryable message.
      setError(toGenerationError(caught));
    } finally {
      if (requestIdRef.current === requestId) {
        setIsGenerating(false);
      }
    }
  }, [config, categoryName, isConfigured, onSetCards]);

  // Auto-generate once on entry when we have a key and no cards yet (e.g. a
  // resumed draft that already has cards skips this and shows them directly).
  useEffect(() => {
    if (hasAutoGeneratedRef.current) return;
    if (!isConfigured) return;
    if (cards.length > 0) return;
    hasAutoGeneratedRef.current = true;
    void generate();
  }, [isConfigured, cards.length, generate]);

  const handleRerollConfirmed = () => {
    setConfirmReroll(false);
    void generate();
  };

  const cardCount = cards.length;
  const answeredCount = cards.filter((card) => card.answer.trim().length > 0).length;
  const canContinue = answeredCount > 0;
  const countLabel =
    `${String(cardCount)} ${cardCount === 1 ? 'card' : 'cards'}` +
    (answeredCount !== cardCount ? ` (${String(answeredCount)} with an answer)` : '');
  const countDriftsFar =
    cardCount > 0 && Math.abs(cardCount - DEFAULT_CARD_COUNT) > COUNT_WARNING_MARGIN;

  const stepClass = styles['step'] ?? '';
  const introClass = styles['intro'] ?? '';
  const toolbarClass = styles['toolbar'] ?? '';
  const countClass = styles['count'] ?? '';
  const toolbarActionsClass = styles['toolbarActions'] ?? '';
  const warningClass = styles['warning'] ?? '';
  const listWrapClass = styles['listWrap'] ?? '';
  const listClass = styles['list'] ?? '';
  const emptyClass = styles['empty'] ?? '';
  const overlayClass = styles['overlay'] ?? '';
  const spinnerClass = styles['spinner'] ?? '';
  const errorClass = styles['error'] ?? '';
  const errorIconClass = styles['errorIcon'] ?? '';
  const errorMessageClass = styles['errorMessage'] ?? '';
  const errorActionsClass = styles['errorActions'] ?? '';
  const footerClass = styles['footer'] ?? '';
  const confirmBarClass = styles['confirmBar'] ?? '';

  if (!isConfigured) {
    return (
      <div className={stepClass}>
        <p className={introClass}>
          Add your OpenAI key on the credentials step to generate card ideas for &ldquo;
          {categoryName}&rdquo;.
        </p>
      </div>
    );
  }

  return (
    <div className={stepClass}>
      <p className={introClass}>
        Card ideas for &ldquo;{categoryName}&rdquo;. Edit any answer or image prompt, delete cards
        you don&rsquo;t want, add your own, or reroll the whole set. Images come next.
      </p>

      <div className={toolbarClass}>
        <span className={countClass} role="status">
          {countLabel}
        </span>
        <div className={toolbarActionsClass}>
          <Button type="button" variant="secondary" size="small" onClick={onAddCard}>
            + Add card
          </Button>
          <Button
            type="button"
            variant="danger"
            size="small"
            onClick={() => {
              setConfirmReroll(true);
            }}
            disabled={isGenerating}
          >
            🎲 Reroll all
          </Button>
        </div>
      </div>

      {countDriftsFar && (
        <p className={warningClass} role="status">
          This category has {cardCount} cards — sample categories usually carry around{' '}
          {DEFAULT_CARD_COUNT}. That&rsquo;s fine, just a heads-up.
        </p>
      )}

      {confirmReroll && (
        <div className={confirmBarClass} role="alertdialog" aria-label="Confirm reroll all">
          <span>Replace all {cardCount} cards with a fresh set? Your edits will be lost.</span>
          <div className={errorActionsClass}>
            <Button
              type="button"
              variant="secondary"
              size="small"
              onClick={() => {
                setConfirmReroll(false);
              }}
            >
              Cancel
            </Button>
            <Button type="button" variant="danger" size="small" onClick={handleRerollConfirmed}>
              Reroll all
            </Button>
          </div>
        </div>
      )}

      {error !== null && (
        <div className={errorClass} role="alert">
          <span className={errorIconClass} aria-hidden="true">
            ⚠️
          </span>
          <div>
            <p className={errorMessageClass}>{error.message}</p>
            <div className={errorActionsClass}>
              <Button
                type="button"
                variant="secondary"
                size="small"
                onClick={() => {
                  void generate();
                }}
              >
                Retry
              </Button>
            </div>
          </div>
        </div>
      )}

      <div className={listWrapClass}>
        {isGenerating && (
          <div className={overlayClass} role="status" aria-live="polite">
            <span className={spinnerClass} aria-hidden="true">
              ⏳
            </span>
            <span>Generating card ideas…</span>
          </div>
        )}

        {cardCount === 0 && !isGenerating ? (
          <p className={emptyClass}>
            No cards yet. Reroll to generate a fresh set, or add one manually.
          </p>
        ) : (
          <ul className={listClass}>
            {cards.map((card, index) => (
              <CardListItem
                key={card.id}
                card={card}
                position={index + 1}
                onChange={(changes) => {
                  onUpdateCard(card.id, changes);
                }}
                onDelete={() => {
                  onDeleteCard(card.id);
                }}
              />
            ))}
          </ul>
        )}
      </div>

      <div className={footerClass}>
        <Button
          type="button"
          variant="primary"
          onClick={onContinue}
          disabled={!canContinue || isGenerating}
        >
          Continue →
        </Button>
      </div>
    </div>
  );
}
